name: Build LG gram Assistant

on:
  pull_request:
  push:

jobs:
  CI:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Debug Build
        run: xcodebuild -scheme LGgramAssistant -destination "platform=macOS" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
